In [ ]:
! pip install numpy


[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [11]:
import numpy as np

## Ejercicios con libreria numpy

In [ ]:
print(np.__version__)

2.4.2


In [ ]:
z = np.zeros(10) # Generamos una lista de zeros
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
z[4] = 3
print(z)

[0. 0. 0. 0. 3. 0. 0. 0. 0. 0.]


In [ ]:
z[1:5] = 2 # Podemos modificar los valores de un rango en la lista
print(z)

[0. 2. 2. 2. 2. 0. 0. 0. 0. 0.]


In [ ]:
z[5:8] = 3 # Modificamos rango de valores de 5-8, agregamos el valor de 3
print(z)

[0. 2. 2. 2. 2. 3. 3. 3. 0. 0.]


In [ ]:
N = np.arange(10,49) # Creamos valores en un rango del 10 al 49
print(N)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
N = N[::-1] # Invertimos el orden de los elementos en la lista
print(N)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
for n in N: # Podemos iterar sobre los elementos de la lista
    print(n)

48
47
46
45
44
43
42
41
40
39
38
37
36
35
34
33
32
31
30
29
28
27
26
25
24
23
22
21
20
19
18
17
16
15
14
13
12
11
10


In [ ]:
Z = np.arange(0,9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
N = np.arange(0,16).reshape(4,4)
print(N)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
Z = np.eye(4) # Matriz identidad de 4 x 4
print(Z)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
Z = np.random.random((3,3,3)) # Crea una matriz
print(Z)

[[[0.78503929 0.09449507 0.89319646]
  [0.0902122  0.05785038 0.02956169]
  [0.30685082 0.53637457 0.49393966]]

 [[0.43377985 0.16741533 0.56415284]
  [0.83543746 0.76264429 0.83186107]
  [0.92401559 0.02498744 0.02480762]]

 [[0.44403176 0.53100824 0.66211951]
  [0.43531384 0.79823283 0.59188125]
  [0.29862617 0.87212596 0.94879449]]]


In [ ]:
Z = np.random.random((10))
valor_medio = np.mean(Z)
print(valor_medio)
print(Z)

0.5667218968005792
[0.28126656 0.37613494 0.57207725 0.66654613 0.26799034 0.94008417
 0.52295906 0.92486797 0.78618325 0.32910929]


In [ ]:
print(np.nan*0)

nan


In [ ]:
print(np.nan == np.nan)

False


In [ ]:
print(np.inf>np.nan)

False


In [ ]:
Z = np.random.random((10))
N = np.random.random((10))

In [ ]:
print(Z)

[0.47125594 0.4657439  0.44258087 0.41563806 0.34035125 0.25179249
 0.16418355 0.96389187 0.72359831 0.16703263]


In [ ]:
print(N)

[0.8773126  0.86731703 0.46225699 0.58432272 0.72096511 0.162828
 0.45454303 0.27257592 0.505493   0.61668692]


In [ ]:
R = np.dot(Z,N) # Multiplicacion de matrices
print(R)

2.3573624179113004


In [ ]:
print(sum(range(5), -1)) # Suma de los números del 0 al 4 y restamos 1 al resultado

9


In [ ]:
print(list(range(5)))

[0, 1, 2, 3, 4]


In [ ]:
Z = np.random.random((10))
print(Z)

[0.96743124 0.01307031 0.17568213 0.69413744 0.12989837 0.96001469
 0.1201708  0.3451644  0.8420156  0.13740168]


In [ ]:
Z.sort()
print(Z)

[0.01307031 0.1201708  0.12989837 0.13740168 0.17568213 0.3451644
 0.69413744 0.8420156  0.96001469 0.96743124]


In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [ ]:
print(A)

[1 1 0 0 0]


In [ ]:
print(B)

[1 1 1 0 1]


In [ ]:
iguales = np.allclose(A, B) # Compara si dos arreglos son iguales
if iguales

False

In [14]:
n = 10
p = 3
z = np.zeros((n,n))

np.put(z, np.random.choice(range(n*n), p, replace = False),1)
print(z)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [13]:
# Extrae la media de cada fila de la matriz

x = np.random.rand(5, 10)
print(x)

[[0.37643501 0.5095439  0.39632617 0.68427951 0.96330447 0.19976991
  0.91369394 0.18872331 0.7499651  0.7431481 ]
 [0.39322255 0.76238602 0.09408157 0.84384445 0.74423295 0.78262374
  0.59739974 0.05863667 0.89130448 0.00531678]
 [0.29855536 0.27431901 0.09429269 0.52264279 0.3340751  0.70566378
  0.89714004 0.75310954 0.19911709 0.82616735]
 [0.51267269 0.19787848 0.92952049 0.98495914 0.75131616 0.12462945
  0.46000873 0.05468767 0.38312435 0.46956012]
 [0.85612049 0.91358328 0.64437869 0.79889581 0.21618546 0.35757537
  0.35213251 0.27704238 0.25109219 0.27435396]]


In [15]:
#  Como extraer la media de cada fila

y = x.mean(axis = 1).reshape(-1, 1)
print(y)

[[0.57251894]
 [0.5173049 ]
 [0.49050827]
 [0.48683573]
 [0.49413601]]


In [ ]:
# Como saber si una matriz tiene valores nulos

z = np.random.randiant(0,3,(3,10))
print(z)

<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
<>:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
C:\Users\santi\AppData\Local\Temp\ipykernel_12684\2225321173.py:3: SyntaxWarning: 'int' object is not callable; perhaps you missed a comma?
  z = np.random.randiant(0,3(3,10))


AttributeError: module 'numpy.random' has no attribute 'randiant'

In [17]:
# Mostramos si contiene valores nulos en la matriz
print((~Z.any(axis = 0)).any())

NameError: name 'Z' is not defined

In [18]:
# Como encontrar los valores mas frecuentes en un arreglo
z = np.random.randiant(5,10,50)
print(z)

AttributeError: module 'numpy.random' has no attribute 'randiant'

In [19]:
# Como encontrar los valores mas frecuentes en un arreglo
z = np.random.randint(5,10,10)
print(z)

[8 9 9 8 7 9 8 6 9 7]


In [20]:
print(np.bincount(z).argmin()) # Detectar el valor que menos aparece

0


In [21]:
z = np.random.random((10,2))
x, y = z[:,0],z[:,1]

print(z)

[[0.29373063 0.93943039]
 [0.85151119 0.72037663]
 [0.1187349  0.78173603]
 [0.22162578 0.10581681]
 [0.45295396 0.16200049]
 [0.71217999 0.93802498]
 [0.63276967 0.38985355]
 [0.91482945 0.19980289]
 [0.77584436 0.38619071]
 [0.78077866 0.28395912]]


In [22]:
print(x)

[0.29373063 0.85151119 0.1187349  0.22162578 0.45295396 0.71217999
 0.63276967 0.91482945 0.77584436 0.78077866]


In [31]:
R = np.sqrt(x**2+y**2)
T = np.arctan(y,x)
print(R)
print(T)

[0.98428002 1.11535367 0.79070171 0.2455915  0.48105244 1.17774836
 0.74322489 0.93639421 0.86664742 0.83081171]
[0.7541777  0.62427106 0.66350474 0.10542449 0.1606052  0.75343061
 0.37172895 0.19720602 0.36854543 0.27667621]


In [32]:
z = np.random.random(10)
print(z)

z[z.argmax()] = 0
print(z)

[0.61929852 0.45961337 0.14402332 0.72687339 0.58342387 0.89769921
 0.24058658 0.43733612 0.49009729 0.73957851]
[0.61929852 0.45961337 0.14402332 0.72687339 0.58342387 0.
 0.24058658 0.43733612 0.49009729 0.73957851]


In [34]:
# Construye la martriz de Cauchy
x = np.arange(15)
print(x)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
-9391966.027650956


In [58]:
# Simular una ecuacion cuadratica, con valores aleatorios y encontrar la solucion con formula general
# [4,2,4]

a = np.random.randint(1,10)
b = np.random.randint(1,10)
c = np.random.randint(1,10)

print(f"Valores de la ecuación cuadrática: a = {a}, b = {b}, c = {c}")

discriminante = b**2 - 4*a*c
if discriminante >= 0:
    raiz_discriminante = np.sqrt(discriminante)
    x1 = (-b + raiz_discriminante) / (2*a)
    x2 = (-b - raiz_discriminante) / (2*a)
    print(f"Las soluciones de la ecuación cuadrática son: x1 = {x1}, x2 = {x2}")
else:
    print("La ecuación cuadrática no tiene solucion")


Valores de la ecuación cuadrática: a = 1, b = 5, c = 6
Las soluciones de la ecuación cuadrática son: x1 = -2.0, x2 = -3.0
